"$schema" = "schemas/schema.json"
[default]
description = """
This permission set configures which
torch features are by default exposed.

#### Granted Permissions

It allows access to all torch commands.
"""
permissions = ["allow-ping", "allow-toggle", "allow-check"]
